[supervisord]
nodaemon=true

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x720x24
priority=1
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:xfce]
command=/usr/bin/startxfce4
environment=DISPLAY=:1
priority=2
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -nopw -shared
priority=3
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc/ 8080 localhost:5900
priority=4
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
